# Let's play: Try to guess the number randomly generated by the machine

from random import randint

num = randint(0, 1000)
shot = int(input('Try to guess the integer number: '))

while num != shot:
    if shot > num:
        print('The number is smaller')
        shot = int(input('Try to guess the integer number: '))
    else:
        print('The number is higher')
        shot = int(input('Try to guess the integer number: '))

print(f'Nice! The number is {num}')
